require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
use_modular_headers!
target 'schoolplus' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'schoolplusTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)


    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
    
    
    # Patch Boost to remove std::unary_function dependency
      boost_file_path = 'Pods/boost/boost/container_hash/hash.hpp'
      if File.exist?(boost_file_path)
        text = File.read(boost_file_path)
        new_contents = text.gsub(
          /struct hash_base : std::unary_function<T, std::size_t> \{\};/,
          'struct hash_base { using argument_type = T; using result_type = std::size_t; };'
        )
        File.open(boost_file_path, "w") { |file| file.puts new_contents }
      end
  end
end
